import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { getFirestore, collection, addDoc, getDocs, query, where, updateDoc, doc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const root=document.querySelector('#app');
const toast=document.querySelector('#toast');
const fb=initializeApp(firebaseConfig),auth=getAuth(fb),db=getFirestore(fb);
const app={user:null,role:'',type:'DRY',size:'20FT',types:['DRY'],sizes:['20FT','40FT'],condition:'정상',selected:null,photo:null,hidden:new Set()};
const notify=(text)=>{toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)};
const icon=(name)=>({box:'▣',map:'⌖',camera:'◉',shield:'✓',arrow:'→',clock:'◷',file:'▤'}[name]||'•');
const header=(title,back)=>`<header><button id="back">‹</button><b>${title}</b><button id="home">⌂</button></header>`;
function bindHeader(back=dashboard){document.querySelector('#home').onclick=dashboard;document.querySelector('#back').onclick=back}
async function connect(){if(app.user)return true;try{app.user=(await signInAnonymously(auth)).user;return true}catch(e){console.error(e);notify('Firebase 연결에 실패했습니다.');return false}}

function login(){root.innerHTML=`<section class="login-view"><div class="logo"><span>▣</span> CONTAINER LINK</div><div class="login-copy"><p>빈 컨테이너의 이동을 연결하다</p><h1>공컨 매칭부터<br>검수·승인까지</h1><p class="muted">부산항 공컨테이너 실시간 매칭 플랫폼</p></div><label>이메일</label><input value="demo@containerlink.kr" aria-label="이메일"><label>비밀번호</label><input type="password" value="1234" aria-label="비밀번호"><button class="button main" id="signin">시작하기</button><button class="button ghost" id="demo">데모로 둘러보기</button><small>시연용 앱입니다. 실제 개인정보는 입력하지 마세요.</small></section>`;const start=async()=>{if(await connect())roleSelect()};document.querySelector('#signin').onclick=start;document.querySelector('#demo').onclick=start}
function roleSelect(){root.innerHTML=`<section class="role-view"><div class="logo"><span>▣</span> CONTAINER LINK</div><div class="progress"><i></i><i class="on"></i><i></i></div><p class="eyebrow">업무 선택</p><h1>어떤 업무를<br>하시나요?</h1><button class="role-card carrier" id="carrier"><span class="role-icon">▣</span><b>공컨테이너 운반자</b><small>보유한 공컨테이너를 전달합니다</small><em>→</em></button><button class="role-card requester" id="requester"><span class="role-icon">⌁</span><b>컨테이너가 필요해요</b><small>필요한 공컨테이너를 요청합니다</small><em>→</em></button></section>`;document.querySelector('#carrier').onclick=()=>{app.role='carrier';dashboard()};document.querySelector('#requester').onclick=()=>{app.role='requester';dashboard()}}

async function dashboard(){const mine=await ownRequests();root.innerHTML=`<section class="dashboard"><div class="top"><div><p class="eyebrow">${app.role==='carrier'?'공컨테이너 운반자':'컨테이너 필요자'}</p><h1>안녕하세요,<br>김기사님</h1></div><button id="switch">역할 변경</button></div><div class="hero"><span>오늘의 공차 절감 예상</span><b>12.4 <small>km</small></b><p>추천 매칭을 통해 줄일 수 있는 이동거리</p></div><h2>진행 중인 매칭과 운송</h2><div class="mine-list">${mine.length?mine.slice(0,3).map(requestCard).join(''):'<div class="empty">아직 진행 중인 요청이 없습니다.<br>새 요청 또는 매칭 검색을 시작해 보세요.</div>'}</div><button class="action-row" id="action"><span>${app.role==='carrier'?icon('map'):icon('box')}</span><div><b>${app.role==='carrier'?'매칭 찾기':'공컨테이너 요청 등록'}</b><small>${app.role==='carrier'?'Firebase의 실제 요청을 검색합니다':'필요한 컨테이너 조건을 등록합니다'}</small></div><em>›</em></button></section>`;document.querySelector('#switch').onclick=roleSelect;document.querySelector('#action').onclick=()=>app.role==='carrier'?spec('carrier'):spec('requester')}
function requestCard(x){return `<article class="mini-card"><div><b>${x.size||'20FT'} ${x.type||'DRY'}</b><span>${x.pickup||'부산신항'} → ${x.returnPlace||'감만CY'}</span></div><em class="state ${x.status||'open'}">${statusText(x.status)}</em></article>`}
function statusText(s){return({open:'매칭 대기',approval:'승인 대기',confirmed:'매칭 확정',rejected:'거절됨'})[s]||'진행 중'}
async function ownRequests(){if(!await connect())return[];try{const r=await getDocs(query(collection(db,'containerRequests'),where('ownerId','==',app.user.uid)));return r.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.error(e);return[]}}

function spec(kind){const isCarrier=kind==='carrier';root.innerHTML=header(isCarrier?'보유 컨테이너 등록':'필요 컨테이너 선택',dashboard)+`<section class="form-view"><div class="step">2 / 3 <span></span></div><h1>${isCarrier?'보유한':'필요한'} 컨테이너를<br>선택해 주세요</h1><p class="muted">컨테이너 조건을 선택하면 적합한 공컨을 찾아드립니다.</p><h3>컨테이너 타입</h3><div class="option-grid type-grid">${['DRY','REEFER','OPEN TOP','FLAT RACK'].map(v=>`<button class="option ${app.type===v?'selected':''}" data-type="${v}"><i>${v==='DRY'?'▣':v==='REEFER'?'❄':'▤'}</i>${v}</button>`).join('')}</div><h3>사이즈</h3><div class="option-grid two">${['20FT','40FT'].map(v=>`<button class="option ${app.size===v?'selected':''}" data-size="${v}">${v}</button>`).join('')}</div>${isCarrier?`<h3>컨테이너 상태</h3><div class="option-grid two"><button class="option ${app.condition==='정상'?'selected good':''}" data-condition="정상">✓ 정상</button><button class="option ${app.condition==='확인 필요'?'selected warn':''}" data-condition="확인 필요">! 확인 필요</button></div>`:''}<div class="sticky"><button class="button main" id="next">${isCarrier?'매칭 조건 저장':'이 조건으로 요청 등록'}</button></div></section>`;bindHeader(dashboard);document.querySelectorAll('[data-type]').forEach(x=>x.onclick=()=>{app.type=x.dataset.type;spec(kind)});document.querySelectorAll('[data-size]').forEach(x=>x.onclick=()=>{app.size=x.dataset.size;spec(kind)});document.querySelectorAll('[data-condition]').forEach(x=>x.onclick=()=>{app.condition=x.dataset.condition;spec(kind)});document.querySelector('#next').onclick=()=>isCarrier?matchList():requestForm()}
function requestForm(){root.innerHTML=header('공컨테이너 요청 등록',()=>spec('requester'))+`<form class="form-view" id="requestForm"><div class="request-summary"><b>${app.size} ${app.type}</b><span>선택한 컨테이너 조건</span></div><h2>운송 조건을 입력해 주세요</h2><label>희망 인수 장소<input id="pickup" value="부산신항" required></label><label>반납지<input id="returnPlace" value="감만CY" required></label><label>희망 인수 시간<input id="time" type="datetime-local" required></label><label>필요 수량<select id="quantity"><option value="1">1대</option><option value="2">2대</option><option value="3">3대</option></select></label><div class="sticky"><button class="button main">Firebase에 요청 등록</button></div></form>`;bindHeader(()=>spec('requester'));document.querySelector('#requestForm').onsubmit=saveRequest}
async function saveRequest(e){e.preventDefault();if(!await connect())return;const f=e.currentTarget;try{await addDoc(collection(db,'containerRequests'),{ownerId:app.user.uid,type:app.type,size:app.size,condition:'미검수',pickup:f.querySelector('#pickup').value.trim(),returnPlace:f.querySelector('#returnPlace').value.trim(),time:f.querySelector('#time').value,quantity:f.querySelector('#quantity').value,status:'open',createdAt:serverTimestamp()});notify('요청이 Firebase에 등록되었습니다.');dashboard()}catch(err){console.error(err);notify('저장에 실패했습니다. Firestore 규칙을 확인해 주세요.')}}

async function matchList(){root.innerHTML=header('매칭 찾기',()=>spec('carrier'))+`<section class="match-view"><div class="filters"><button class="active">${app.size} · ${app.type}</button><button>거리순</button><button>마감 임박</button></div><div class="map"><div class="pin a">부산신항</div><div class="line"></div><div class="pin b">감만CY</div><small>실시간 위치 기반 추천</small></div><div id="matchResults" class="results"><p class="loading">Firebase 요청을 불러오는 중…</p></div></section>`;bindHeader(()=>spec('carrier'));let rows=[];try{const r=await getDocs(query(collection(db,'containerRequests'),where('status','==','open')));rows=r.docs.map(d=>({id:d.id,...d.data()})).filter(x=>!app.hidden.has(x.id)&&x.type===app.type&&x.size===app.size)}catch(e){console.error(e);notify('요청을 불러오지 못했습니다.')};const box=document.querySelector('#matchResults');box.innerHTML=rows.length?rows.map((x,i)=>`<button class="match-card" data-id="${x.id}"><span class="rank">${i+1}</span><div><b>${x.pickup} <i>→</i> ${x.returnPlace}</b><small>${x.size} ${x.type} · ${x.time?new Date(x.time).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'시간 협의'}</small><em>${x.condition==='정상'?'승인 가능':'상태 확인 필요'}</em></div><strong>${96-i*3}<small>매칭도</small></strong></button>`).join(''):'<div class="empty">현재 조건에 맞는 요청이 없습니다.<br>필요자 역할에서 요청을 먼저 등록해 주세요.</div>';document.querySelectorAll('.match-card').forEach(b=>b.onclick=()=>{app.selected=rows.find(x=>x.id===b.dataset.id);matchDetail()})}
function matchDetail(){const x=app.selected;root.innerHTML=header('매칭 적합도 상세',matchList)+`<section class="detail"><div class="route"><span>${icon('map')} ${x.pickup} → ${x.returnPlace}</span><b>${x.size} ${x.type}</b><div><strong>92<small>점</small></strong><em>매우 적합</em></div></div><p class="info">매칭 적합도는 인수 시간, 인수 위치, 선사 조건을 종합해 계산됩니다.</p><h2>매칭 분석</h2><div class="analysis"><p><span>⌖</span><b>추가 이동거리</b><em>2.1km</em></p><p><span>◷</span><b>희망 인수 시간</b><em>오늘 ${x.time?new Date(x.time).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):'협의'}</em></p><p><span>▤</span><b>선사 승인</b><em>사전 확인 필요</em></p></div><div class="sticky"><button class="button main" id="requestMatch">이 조건으로 매칭 요청</button><button class="button ghost" id="other">다른 매칭 보기</button></div></section>`;bindHeader(matchList);document.querySelector('#requestMatch').onclick=approval;document.querySelector('#other').onclick=matchList}
function approval(){root.innerHTML=header('재사용 승인 요청',matchDetail)+`<section class="approval"><div class="approval-hero"><span>재사용 승인 요청</span><b>${app.selected.pickup} → ${app.selected.returnPlace}</b><small>${app.selected.size} ${app.selected.type}</small></div><h2>선사 제출 정보</h2><div class="accordion">${[['컨테이너 번호','예: ABCD 1234567'],['인수 기사 정보','기사 성명 또는 차량번호'],['이동 경로',`${app.selected.pickup} → ${app.selected.returnPlace}`],['AI 상태 리포트','사진 촬영 후 자동 첨부']].map(([t,p],i)=>`<button class="fold" data-fold="${i}"><span>✓</span>${t}<b>›</b></button><div class="fold-body" id="fold${i}"><input placeholder="${p}"><button>저장</button></div>`).join('')}</div><label class="shipping">선사 선택<select><option>HMM</option><option>OOCL</option><option>MSC</option><option>ONE</option></select></label><p class="notice">승인 전에는 배차가 최종 확정되지 않습니다.</p><button class="button main" id="sendApproval">선사에 승인 요청 보내기</button></section>`;bindHeader(matchDetail);document.querySelectorAll('.fold').forEach(b=>b.onclick=()=>document.querySelector('#fold'+b.dataset.fold).classList.toggle('open'));document.querySelector('#sendApproval').onclick=async()=>{try{await updateDoc(doc(db,'containerRequests',app.selected.id),{status:'approval'});app.selected.status='approval'}catch(e){console.error(e)}notify('승인 요청을 전송했습니다.');inspection()}}
function inspection(){root.innerHTML=header('컨테이너 상태 촬영',approval)+`<section class="inspection"><div class="capture-frame" id="capture"><span>◉</span><b>컨테이너 사진 촬영</b><small>전면 · 측면 · 도어를 순서대로 촬영해 주세요.</small><img id="preview" class="hidden" alt="컨테이너 촬영 사진"></div><input id="photo" type="file" accept="image/*" capture="environment" hidden><div class="ai-report"><span>✦ AI 분석</span><b id="aiText">사진을 등록하면 외관 상태를 분석합니다.</b><small>AI 분석은 분쟁 증빙을 위한 보조 수단입니다.</small></div><button class="button main" id="sendReport">사진 및 AI 리포트 전송</button></section>`;bindHeader(approval);document.querySelector('#capture').onclick=()=>document.querySelector('#photo').click();document.querySelector('#photo').onchange=e=>{const file=e.target.files[0];if(!file)return;app.photo=file;const img=document.querySelector('#preview');img.src=URL.createObjectURL(file);img.classList.remove('hidden');document.querySelector('#aiText').textContent='분석 결과: 파손 의심 없음'};document.querySelector('#sendReport').onclick=()=>{if(!app.photo)return notify('먼저 컨테이너 사진을 촬영해 주세요.');confirmation()}}
function confirmation(){root.innerHTML=header('상태 확인 및 최종 결정',inspection)+`<section class="confirm"><div class="confirm-head"><span>✓ 선사 승인 완료</span><b>${app.selected.size} ${app.selected.type}</b><small>${app.selected.pickup} → ${app.selected.returnPlace}</small></div><h2>검수 사진</h2><img class="confirm-photo" src="${URL.createObjectURL(app.photo)}" alt="검수 사진"><div class="result"><span>✓</span><div><b>AI 분석 결과: 정상</b><small>특이 파손이 발견되지 않았습니다.</small></div></div><label class="check"><input type="checkbox" id="checked"> 사진과 상태 정보를 확인했습니다.</label><button class="button ghost danger" id="reject">매칭 거절</button><button class="button main" id="confirm">매칭 최종 확정</button></section>`;bindHeader(matchList);document.querySelector('#reject').onclick=()=>finish('rejected');document.querySelector('#confirm').onclick=()=>{if(!document.querySelector('#checked').checked)return notify('사진과 상태 정보를 확인해 주세요.');finish('confirmed')}}
async function finish(status){try{await updateDoc(doc(db,'containerRequests',app.selected.id),{status});if(status==='rejected')app.hidden.add(app.selected.id)}catch(e){console.error(e)}notify(status==='confirmed'?'매칭이 최종 확정되었습니다.':'매칭을 거절했습니다.');matchList()}
login();

/* 다중 조건 선택과 전체 목록 표시를 위한 화면 재정의 */
async function dashboard(){const mine=await ownRequests();root.innerHTML=`<section class="dashboard"><div class="top"><div><p class="eyebrow">${app.role==='carrier'?'공컨테이너 운반자':'컨테이너 필요자'}</p><h1>안녕하세요,<br>김기사님</h1></div><button id="switch">역할 변경</button></div><div class="hero"><span>오늘의 공차 절감 예상</span><b>12.4 <small>km</small></b><p>추천 매칭을 통해 줄일 수 있는 이동거리</p></div><h2>진행 중인 매칭과 운송</h2><div class="mine-list">${mine.length?mine.map(requestCard).join(''):'<div class="empty">아직 진행 중인 요청이 없습니다.<br>새 요청 또는 매칭 검색을 시작해 보세요.</div>'}</div><button class="action-row" id="action"><span>${app.role==='carrier'?icon('map'):icon('box')}</span><div><b>${app.role==='carrier'?'매칭 찾기':'공컨테이너 요청 등록'}</b><small>${app.role==='carrier'?'Firebase의 실제 요청을 검색합니다':'필요한 컨테이너 조건을 등록합니다'}</small></div><em>›</em></button></section>`;document.querySelector('#switch').onclick=roleSelect;document.querySelector('#action').onclick=()=>app.role==='carrier'?spec('carrier'):spec('requester')}
function spec(kind){const isCarrier=kind==='carrier';root.innerHTML=header(isCarrier?'보유 컨테이너 등록':'필요 컨테이너 선택',dashboard)+`<section class="form-view"><div class="step">2 / 3 <span></span></div><h1>${isCarrier?'보유한':'필요한'} 컨테이너를<br>선택해 주세요</h1><p class="muted">원하는 조건을 여러 개 선택하면 해당 조건의 매칭을 함께 보여드립니다.</p><h3>컨테이너 타입 <small class="multi-hint">복수 선택</small></h3><div class="option-grid type-grid">${['DRY','REEFER','OPEN TOP','FLAT RACK'].map(v=>`<button class="option ${app.types.includes(v)?'selected':''}" data-type="${v}"><i>${v==='DRY'?'▣':v==='REEFER'?'❄':'▤'}</i>${v}</button>`).join('')}</div><h3>사이즈 <small class="multi-hint">복수 선택</small></h3><div class="option-grid two">${['20FT','40FT'].map(v=>`<button class="option ${app.sizes.includes(v)?'selected':''}" data-size="${v}">${v}</button>`).join('')}</div>${isCarrier?`<h3>컨테이너 상태</h3><div class="option-grid two"><button class="option ${app.condition==='정상'?'selected good':''}" data-condition="정상">✓ 정상</button><button class="option ${app.condition==='확인 필요'?'selected warn':''}" data-condition="확인 필요">! 확인 필요</button></div>`:''}<div class="sticky"><button class="button main" id="next">${isCarrier?'선택 조건으로 매칭 찾기':'이 조건으로 요청 등록'}</button></div></section>`;bindHeader(dashboard);document.querySelectorAll('[data-type]').forEach(x=>x.onclick=()=>{const v=x.dataset.type;if(app.types.includes(v)&&app.types.length>1)app.types=app.types.filter(t=>t!==v);else if(!app.types.includes(v))app.types.push(v);app.type=v;spec(kind)});document.querySelectorAll('[data-size]').forEach(x=>x.onclick=()=>{const v=x.dataset.size;if(app.sizes.includes(v)&&app.sizes.length>1)app.sizes=app.sizes.filter(s=>s!==v);else if(!app.sizes.includes(v))app.sizes.push(v);app.size=v;spec(kind)});document.querySelectorAll('[data-condition]').forEach(x=>x.onclick=()=>{app.condition=x.dataset.condition;spec(kind)});document.querySelector('#next').onclick=()=>isCarrier?matchList():requestForm()}
async function matchList(){root.innerHTML=header('매칭 찾기',()=>spec('carrier'))+`<section class="match-view"><div class="filters"><button class="active">${app.types.join(' · ')}</button><button>${app.sizes.join(' · ')}</button><button>거리순</button></div><div class="map"><div class="pin a">부산신항</div><div class="line"></div><div class="pin b">감만CY</div><small>선택한 복수 조건 기준 추천</small></div><div id="matchResults" class="results"><p class="loading">Firebase 요청을 불러오는 중…</p></div></section>`;bindHeader(()=>spec('carrier'));let rows=[];try{const r=await getDocs(query(collection(db,'containerRequests'),where('status','==','open')));rows=r.docs.map(d=>({id:d.id,...d.data()})).filter(x=>!app.hidden.has(x.id)&&app.types.includes(x.type)&&app.sizes.includes(x.size))}catch(e){console.error(e);notify('요청을 불러오지 못했습니다.')};const box=document.querySelector('#matchResults');box.innerHTML=rows.length?rows.map((x,i)=>`<button class="match-card" data-id="${x.id}"><span class="rank">${i+1}</span><div><b>${x.pickup} <i>→</i> ${x.returnPlace}</b><small>${x.size} ${x.type} · ${Number(x.price||0).toLocaleString('ko-KR')}원</small><em>${x.condition==='정상'?'승인 가능':'상태 확인 필요'}</em></div><strong>${Math.max(70,96-i*3)}<small>매칭도</small></strong></button>`).join(''):'<div class="empty">선택한 조건에 맞는 요청이 없습니다.<br>조건을 추가하거나 변경해 보세요.</div>';document.querySelectorAll('.match-card').forEach(b=>b.onclick=()=>{app.selected=rows.find(x=>x.id===b.dataset.id);matchDetail()})}
